/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 car.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGlobalContext } from '../../../components/App/context'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/customize/car-transformed.glb')
  const {state}=useGlobalContext();
  const {roofbox, color, spoiler}=state.modelcustomize;
  return (
    <group {...props} dispose={null}>
      {
        roofbox===1&&<group position={[1.8, 133.2, -43.27]} rotation={[-1.61, 0, -1.58]} scale={2.89}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Hard_Rough_Plastic_Black_1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Hard_Shiny_Plastic_Grey_2}  />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Hard_Shiny_Plastic_Red_2} />
      </group>
      }
      {
        spoiler===1&&<group position={[0, 49.91, -246.17]} rotation={[-Math.PI / 2, 0, -3.13]} scale={90.48}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Hard_Rough_Plastic_Black_1} position={[0, 2.49, 0]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Hard_Rough_Plastic_Black_1} position={[0, 2.49, 0]} />
      </group>
      }
      {
        spoiler===3&&<group position={[0, 98.84, -230.58]} rotation={[-Math.PI / 2, 0, 0]} scale={[76.27, 12.49, 76.27]}>
        <mesh geometry={nodes.Plane_Carbon_0.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Plane_Feet_0.geometry} material={materials.Feet} />
      </group>
      }
      {
        spoiler===2&&<group position={[0, 121.04, -232.69]} rotation={[-Math.PI / 2, 0, 0]} scale={[70.36, 49.76, 70.36]}>
        <mesh geometry={nodes.Universal_spoiler_1_Carbon_0.geometry} material={materials['Carbon.001']} />
        <mesh geometry={nodes.Universal_spoiler_1_Feet_0.geometry} material={materials['Feet.001']} />
      </group>
      }
      
      
      
      
      <group position={[-36.98, 47.7, -83.64]} rotation={[Math.PI / 2, 0, 0]} scale={-100}>
        <mesh geometry={nodes['Car_seat_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Car_seat_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Car_seat_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[41.39, 47.7, 3.26]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['Car_seat004_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Car_seat004_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Car_seat004_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[41.39, 47.7, -83.64]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['Car_seat006_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Car_seat006_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Car_seat006_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[-36.98, 47.7, 3.26]} rotation={[Math.PI / 2, 0, 0]} scale={-100}>
        <mesh geometry={nodes['Car_seat007_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Car_seat007_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Car_seat007_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[43.76, 97.95, 70.93]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['Dashboard001_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Dashboard001_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Dashboard001_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Dashboard001_Screen_(cube_projection_15)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Dashboard001_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[102.17, 3.09, -16.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.68, 100, 100]}>
        <mesh geometry={nodes['Door002_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Door002_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door002_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Door002_Screen_(cube_projection_15)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door002_SHC_Procedural_metallic_Car_Paint_2_(cube_projection_1'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Door002_Tinted_car_glass_(cube_projection_50)_0'].geometry} material={materials.Tinted_car_glass_cube_projection_50} />
        <mesh geometry={nodes['Door002_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[102.17, 3.09, 83.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.68, 100, 100]}>
        <mesh geometry={nodes['Door003_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Door003_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door003_Car_glass_(cube_projection_50)_0'].geometry} material={materials.Car_glass_cube_projection_50} />
        <mesh geometry={nodes.Door003_Lens_glass_0.geometry} material={materials.Lens_glass} />
        <mesh geometry={nodes.Door003_Lens_0.geometry} material={materials.Lens} />
        <mesh geometry={nodes['Door003_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Door003_Screen_(cube_projection_15)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door003_SHC_Procedural_metallic_Car_Paint_2_(cube_projection_1'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Door003_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[-97.83, 3.09, -16.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.68, 100, 100]}>
        <mesh geometry={nodes['Door006_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Door006_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door006_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Door006_Screen_(cube_projection_15)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door006_SHC_Procedural_metallic_Car_Paint_2_(cube_projection_1'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Door006_Tinted_car_glass_(cube_projection_50)_0'].geometry} material={materials.Tinted_car_glass_cube_projection_50} />
        <mesh geometry={nodes['Door006_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[-97.83, 3.09, 83.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.68, 100, 100]}>
        <mesh geometry={nodes['Door008_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Door008_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door008_Car_glass_(cube_projection_50)_0'].geometry} material={materials.Car_glass_cube_projection_50} />
        <mesh geometry={nodes.Door008_Lens_glass_0.geometry} material={materials.Lens_glass} />
        <mesh geometry={nodes.Door008_Lens_0.geometry} material={materials.Lens} />
        <mesh geometry={nodes['Door008_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Door008_Screen_(cube_projection_15)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Door008_SHC_Procedural_metallic_Car_Paint_2_(cube_projection_1'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Door008_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[2.17, 84.23, 166.33]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['Engine_Black_plastic_(cube_projection_3)_0'].geometry} material={materials.Black_plastic_cube_projection_3} />
        <mesh geometry={nodes['Engine_Metal_(cube_projection_5)_0'].geometry} material={materials.Metal_cube_projection_5} material-color={color}/>
      </group>
      <group position={[-43.23, -24.93, 209.72]} rotation={[-Math.PI / 2, 0, 0]} scale={15.06}>
        <mesh geometry={nodes['extra_engine_details001_Black_plastic_(cube_projection_3)_0'].geometry} material={materials.Black_plastic_cube_projection_3} />
        <mesh geometry={nodes['extra_engine_details001_Metal_(cube_projection_5)_0'].geometry} material={materials.Metal_cube_projection_5} material-color={color} />
      </group>
      <group position={[2.17, 93.09, 103.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.68, 100, 100]}>
        <mesh geometry={nodes['Main_body005_Black_plastic_(cube_projection_3)_0'].geometry} material={materials.Black_plastic_cube_projection_3} />
        <mesh geometry={nodes['Main_body005_SHC_Procedural_metallic_Car_Paint_2_(cube_project'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} material-color={color} />
      </group>
      <group position={[2.17, 123.09, -138.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.68, 100, 100]}>
        <mesh geometry={nodes['Main_body007_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes.Main_body007_Glass_black_edge_0.geometry} material={materials.Glass_black_edge} />
        <mesh geometry={nodes.Main_body007_Lens_glass_0.geometry} material={materials.Lens_glass} />
        <mesh geometry={nodes.Main_body007_Lens_0.geometry} material={materials.Lens} />
        <mesh geometry={nodes['Main_body007_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Main_body007_SHC_Procedural_metallic_Car_Paint_2_(cube_project'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Main_body007_Tinted_car_glass_(cube_projection_50)_0'].geometry} material={materials.Tinted_car_glass_cube_projection_50} />
        <mesh geometry={nodes['Main_body007_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[2.17, 3.09, -16.46]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.68, 100, 100]}>
        <mesh geometry={nodes['Main_body019_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Main_body019_Black_leather_(cube_projection_3)_0001'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Main_body019_Black_plastic_(cube_projection_3)_0'].geometry} material={materials.Black_plastic_cube_projection_3} />
        <mesh geometry={nodes['Main_body019_Black_plastic_(cube_projection_3)_0001'].geometry} material={materials.Black_plastic_cube_projection_3} />
        <mesh geometry={nodes['Main_body019_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Main_body019_Car_glass_(cube_projection_50)_0'].geometry} material={materials.Car_glass_cube_projection_50} />
        <mesh geometry={nodes['Main_body019_Car_led_headlights_(cube_projection_5)_0'].geometry} material={materials.Car_led_headlights_cube_projection_5} />
        <mesh geometry={nodes.Main_body019_Glass_black_edge_0.geometry} material={materials.Glass_black_edge} />
        <mesh geometry={nodes['Main_body019_Led_Ring_headlights_(cube_projection_5)_0'].geometry} material={materials.Led_Ring_headlights_cube_projection_5} />
        <mesh geometry={nodes.Main_body019_Lens_glass_0.geometry} material={materials.Lens_glass} />
        <mesh geometry={nodes.Main_body019_Lens_0.geometry} material={materials.Lens} />
        <mesh geometry={nodes['Main_body019_Light_Housing_(cube_projection_5)_0'].geometry} material={materials.Light_Housing_cube_projection_5} />
        <mesh geometry={nodes['Main_body019_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Main_body019_Matte_chrome_(cube_projection_10)_0001'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Main_body019_Metal_(cube_projection_5)_0'].geometry} material={materials.Metal_cube_projection_5} />
        <mesh geometry={nodes['Main_body019_Rear_led_bar_(cube_projection_5)_0'].geometry} material={materials.Rear_led_bar_cube_projection_5} />
        <mesh geometry={nodes['Main_body019_Screen_(cube_projection_15)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Main_body019_SHC_Procedural_metallic_Car_Paint_2_(cube_pro'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Main_body019_SHC_Procedural_metallic_Car_Paint_2_(cube_pro001'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Main_body019_SHC_Procedural_metallic_Car_Paint_2_(cube_project'].geometry} material={materials.SHC_Procedural_metallic_Car_Paint_2_cube_projection_10} />
        <mesh geometry={nodes['Main_body019_Tinted_car_glass_(cube_projection_50)_0'].geometry} material={materials.Tinted_car_glass_cube_projection_50} />
        <mesh geometry={nodes['Main_body019_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <group position={[41.39, 88.8, 32.77]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['Steering_wheel002_Black_leather_(cube_projection_3)_0'].geometry} material={materials.Black_leather_cube_projection_3} />
        <mesh geometry={nodes['Steering_wheel002_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} />
        <mesh geometry={nodes['Steering_wheel002_Screen_(cube_projection_15)_0'].geometry} material={materials.Black_Trim_cube_projection_50} />
        <mesh geometry={nodes['Steering_wheel002_White_leather_(cube_projection_3)_0'].geometry} material={materials.White_leather_cube_projection_3} />
      </group>
      <mesh geometry={nodes.Brake_caliper_SHC_Procedural_brake_caliper_paint_0.geometry} material={materials.SHC_Procedural_brake_caliper_paint} position={[-84.27, 37.54, 156.82]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={80.92} />
      <mesh geometry={nodes.Brake_caliper001_SHC_Procedural_brake_caliper_paint_0.geometry} material={materials.SHC_Procedural_brake_caliper_paint} position={[88.42, 37.54, -150.98]} rotation={[-Math.PI / 2, 0, 0]} scale={80.92} />
      <mesh geometry={nodes.Brake_caliper002_SHC_Procedural_brake_caliper_paint_0.geometry} material={materials.SHC_Procedural_brake_caliper_paint} position={[-84.27, 37.54, -151.06]} rotation={[Math.PI / 2, 0, Math.PI]} scale={80.92} />
      <mesh geometry={nodes.Brake_caliper003_SHC_Procedural_brake_caliper_paint_0.geometry} material={materials.SHC_Procedural_brake_caliper_paint} position={[88.42, 37.54, 156.9]} rotation={[Math.PI / 2, 0, 0]} scale={80.92} />
      <mesh geometry={nodes['Brakedisk_Metal_(cube_projection_5)_0'].geometry} material={materials.Metal_cube_projection_5} position={[-84.34, 37.54, -151.06]} rotation={[1.57, 0, Math.PI]} scale={80.92} />
      <mesh geometry={nodes['Brakedisk001_Metal_(cube_projection_5)_0'].geometry} material={materials.Metal_cube_projection_5} position={[-84.34, 37.54, 156.82]} rotation={[-1.57, 0, -Math.PI]} scale={80.92} />
      <mesh geometry={nodes['Brakedisk002_Metal_(cube_projection_5)_0'].geometry} material={materials.Metal_cube_projection_5} position={[88.49, 37.54, -150.98]} rotation={[-1.57, 0, 0]} scale={80.92} />
      <mesh geometry={nodes['Brakedisk003_Metal_(cube_projection_5)_0'].geometry} material={materials.Metal_cube_projection_5} position={[88.49, 37.54, 156.9]} rotation={[1.57, 0, 0]} scale={80.92} />
      <mesh geometry={nodes['Grille003_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[-40.53, 34.47, 249.66]} scale={100} />
      <mesh geometry={nodes['Grille004_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[-76.61, 23.94, 248.41]} scale={100} />
      <mesh geometry={nodes['Grille005_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[90.4, 24.59, -255.68]} rotation={[-Math.PI, 0, -Math.PI]} scale={100} />
      <mesh geometry={nodes.licence_plate001_Licence_plate_0.geometry} material={materials.Licence_plate} position={[2.14, 61.16, -260.35]} rotation={[-1.31, 0, 0]} scale={100} />
      <mesh geometry={nodes['Logo_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[-92.33, 37.47, -151]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.8, 1.11, 0.8]} />
      <mesh geometry={nodes['Logo001_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[41.36, 89.48, 32.07]} rotation={[-2.86, 0, -Math.PI / 2]} scale={100} />
      <mesh geometry={nodes['Logo007_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[96.49, 37.47, 156.84]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.8, 1.11, 0.8]} />
      <mesh geometry={nodes['Logo008_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[96.49, 37.47, -151.04]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.8, 1.11, 0.8]} />
      <mesh geometry={nodes['Logo009_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[2.09, 69.16, 248.16]} rotation={[-0.79, 0, Math.PI / 2]} scale={[2.43, 3.39, 2.43]} />
      <mesh geometry={nodes['Logo011_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[-92.33, 37.47, 156.88]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.8, 1.11, 0.8]} />
      <mesh geometry={nodes['Pedals_Matte_chrome_(cube_projection_10)_0'].geometry} material={materials.Matte_chrome_cube_projection_10} position={[39.96, 28.97, 111.42]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Rim004_Metallic_wheel_0.geometry} material={materials.Metallic_wheel} position={[60.65, 37.46, 156.82]} rotation={[-Math.PI / 2, 0, 0]} scale={101.87} />
      <mesh geometry={nodes.Rim005_Metallic_wheel_0.geometry} material={materials.Metallic_wheel} position={[60.65, 37.46, -151.06]} rotation={[-Math.PI / 2, 0, 0]} scale={101.87} />
      <mesh geometry={nodes.Rim006_Metallic_wheel_0.geometry} material={materials.Metallic_wheel} position={[-56.49, 37.46, -150.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={101.87} />
      <mesh geometry={nodes.Rim007_Metallic_wheel_0.geometry} material={materials.Metallic_wheel} position={[-56.49, 37.46, 156.9]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={101.87} />
      <mesh geometry={nodes['tire_tread004_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[-36.46, 37.46, 156.9]} rotation={[-1.56, 0, -Math.PI]} scale={101.87} />
      <mesh geometry={nodes['tire_tread005_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[-36.46, 37.46, -150.98]} rotation={[-1.56, 0, -Math.PI]} scale={101.87} />
      <mesh geometry={nodes['tire_tread006_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[40.62, 37.46, -151.06]} rotation={[-1.58, 0, 0]} scale={101.87} />
      <mesh geometry={nodes['tire_tread007_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[40.62, 37.46, 156.82]} rotation={[-1.58, 0, 0]} scale={101.87} />
      <mesh geometry={nodes['Tire004_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[-56.49, 37.46, 156.9]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={101.87} />
      <mesh geometry={nodes['Tire005_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[60.65, 37.46, 156.82]} rotation={[-Math.PI / 2, 0, 0]} scale={101.87} />
      <mesh geometry={nodes['Tire006_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[60.65, 37.46, -151.06]} rotation={[-Math.PI / 2, 0, 0]} scale={101.87} />
      <mesh geometry={nodes['Tire007_Tire_(cube_projection_50)_0'].geometry} material={materials.Tire_cube_projection_50} position={[-56.49, 37.46, -150.98]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={101.87} />
      <mesh geometry={nodes['Wiper002_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[37.3, 100.41, 108.81]} rotation={[-2.28, 0, -3.05]} scale={100} />
      <mesh geometry={nodes['Wiper003_Black_Trim_(cube_projection_50)_0'].geometry} material={materials.Black_Trim_cube_projection_50} position={[-34.29, 100.38, 108.67]} rotation={[-2.26, 0.11, 3.01]} scale={100} />
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_21.skeleton} />
      <primitive object={nodes.GLTF_created_0_rootJoint_1} />
      <skinnedMesh geometry={nodes.Object_21001.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_21001.skeleton} />
      <primitive object={nodes.GLTF_created_0_rootJoint_2} />
      <skinnedMesh geometry={nodes.Object_21002.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_21002.skeleton} />
    </group>
  )
}

useGLTF.preload('/models/customize/car-transformed.glb')
