/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 2.glb -T
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGlobalContext } from "../../../components/App/context";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/customize/2-transformed.glb");
  const { state } = useGlobalContext();
  const { wing, ear, glass } = state.modelcustomize;
  return (
    <group {...props} dispose={null}>
      {wing === 1 && (
        <group
          position={[0.04, -0.44, -0.17]}
          rotation={[-Math.PI / 2, 0, -0.01]}
          scale={0.06}
        >
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials["aiStandardSurface1SG.002"]}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials["aiStandardSurface6SG.001"]}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["aiStandardSurface1SG.002"]}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials["aiStandardSurface2SG.002"]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials["aiStandardSurface3SG.002"]}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials["aiStandardSurface4SG.002"]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials["aiStandardSurface6SG.001"]}
          />
        </group>
      )}
      {wing === 4 && (
        <group
          position={[0.03, 0.67, -0.15]}
          rotation={[0, 0.01, 0]}
          scale={0.17}
        >
          <mesh
            geometry={nodes.polySurface44_lambert9_0.geometry}
            material={materials["lambert9.001"]}
          />
          <mesh
            geometry={nodes.polySurface45_lambert9_0.geometry}
            material={materials["lambert9.001"]}
          />
          <mesh
            geometry={nodes.polySurface46_lambert1_0.geometry}
            material={materials["lambert1.001"]}
          />
          <mesh
            geometry={nodes.polySurface50_lambert11_0.geometry}
            material={materials["lambert11.001"]}
          />
          <mesh
            geometry={nodes.polySurface51_lambert10_0.geometry}
            material={materials["lambert10.001"]}
          />
          <mesh
            geometry={nodes.polySurface52_lambert10_0.geometry}
            material={materials["lambert10.001"]}
          />
          <mesh
            geometry={nodes.polySurface53_lambert6_0.geometry}
            material={materials["lambert6.001"]}
          />
          <mesh
            geometry={nodes.polySurface54_lambert8_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface55_lambert6_0.geometry}
            material={materials["lambert6.001"]}
          />
          <mesh
            geometry={nodes.polySurface56_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
          <mesh
            geometry={nodes.polySurface57_lambert8_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface58_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
          <mesh
            geometry={nodes.polySurface59_lambert9_0.geometry}
            material={materials["lambert9.001"]}
          />
          <mesh
            geometry={nodes.polySurface60_lambert9_0.geometry}
            material={materials["lambert9.001"]}
          />
          <mesh
            geometry={nodes.polySurface61_lambert9_0.geometry}
            material={materials["lambert9.001"]}
          />
          <mesh
            geometry={nodes.polySurface62_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
          <mesh
            geometry={nodes.polySurface63_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
          <mesh
            geometry={nodes.polySurface64_lambert1_0.geometry}
            material={materials["lambert1.001"]}
          />
          <mesh
            geometry={nodes.polySurface65_lambert1_0.geometry}
            material={materials["lambert1.001"]}
          />
          <mesh
            geometry={nodes.polySurface66_lambert1_0.geometry}
            material={materials["lambert1.001"]}
          />
          <mesh
            geometry={nodes.polySurface67_lambert11_0.geometry}
            material={materials["lambert11.001"]}
          />
          <mesh
            geometry={nodes.polySurface68_lambert10_0.geometry}
            material={materials["lambert10.001"]}
          />
          <mesh
            geometry={nodes.polySurface69_lambert10_0.geometry}
            material={materials["lambert10.001"]}
          />
          <mesh
            geometry={nodes.polySurface70_lambert6_0.geometry}
            material={materials["lambert6.001"]}
          />
          <mesh
            geometry={nodes.polySurface71_lambert8_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface72_lambert6_0.geometry}
            material={materials["lambert6.001"]}
          />
          <mesh
            geometry={nodes.polySurface73_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
          <mesh
            geometry={nodes.polySurface74_lambert8_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface75_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
          <mesh
            geometry={nodes.polySurface76_lambert9_0.geometry}
            material={materials["lambert9.001"]}
          />
          <mesh
            geometry={nodes.polySurface77_lambert12_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface78_lambert12_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface79_lambert12_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface81_lambert13_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface81_lambert3_0.geometry}
            material={materials["lambert3.001"]}
          />
          <mesh
            geometry={nodes.polySurface81_lambert4_0.geometry}
            material={materials["lambert4.001"]}
          />
          <mesh
            geometry={nodes.polySurface82_lambert1_0.geometry}
            material={materials["lambert1.001"]}
          />
          <mesh
            geometry={nodes.polySurface83_lambert12_0.geometry}
            material={materials["lambert8.001"]}
          />
          <mesh
            geometry={nodes.polySurface84_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
          <mesh
            geometry={nodes.polySurface85_lambert1_0.geometry}
            material={materials["lambert1.001"]}
          />
          <mesh
            geometry={nodes.polySurface86_lambert7_0.geometry}
            material={materials["lambert7.001"]}
          />
        </group>
      )}
      {wing === 3 && (
        <group
          position={[0.04, 0.36, -0.21]}
          rotation={[-Math.PI, 0.01, -Math.PI]}
          scale={1.21}
        >
          <group
            position={[0, 0.75, 0]}
            rotation={[0, 0, 1.57]}
            scale={[0.12, 0.07, 0.04]}
          >
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials["Material.002"]}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["Material.003"]}
            />
          </group>
          <group position={[-0.11, 0.68, -0.47]} scale={0.01}>
            <mesh
              geometry={nodes.Object_62.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              geometry={nodes.Object_63.geometry}
              material={materials["Material.009"]}
            />
          </group>
          <group position={[0.11, 0.74, 0.02]} scale={[0.06, 0.07, 0.06]}>
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group position={[-0.11, 0.74, 0.02]} scale={[0.06, 0.07, 0.06]}>
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials["Material.002"]}
            position={[0, 0.8, 0.04]}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials["Material.002"]}
            position={[0, 0.62, 0.04]}
          />
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials["Material.006"]}
            position={[-0.04, 0.77, 0.05]}
            scale={[-0.01, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials["Material.008"]}
            position={[-0.02, 0.77, 0.05]}
            scale={[-0.01, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials["Material.007"]}
            position={[0, 0.77, 0.05]}
            scale={[-0.01, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials["Material.005"]}
            position={[-0.03, 0.79, 0.05]}
            scale={[-0.02, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials["Material.007"]}
            position={[-0.03, 0.82, 0.05]}
            scale={[-0.02, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_44.geometry}
            material={materials["Material.005"]}
            position={[-0.03, 0.64, 0.05]}
            scale={[-0.02, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_46.geometry}
            material={materials["Material.005"]}
            position={[-0.03, 0.62, 0.05]}
            scale={[-0.02, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_48.geometry}
            material={materials["Material.006"]}
            position={[-0.03, 0.59, 0.05]}
            scale={[-0.02, -0.01, 0]}
          />
          <mesh
            geometry={nodes.Object_58.geometry}
            material={materials["Material.003"]}
            position={[0, 0.83, -0.04]}
            scale={[0.04, 0.04, 0.01]}
          />
          <mesh
            geometry={nodes.Object_60.geometry}
            material={materials["Material.011"]}
            position={[-0.12, 0.66, -0.05]}
            rotation={[0, 0.24, 0]}
            scale={[0.01, 0.07, 0.02]}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials["Material.003"]}
            position={[0, 0.86, 0]}
            scale={[0.98, 1, 1]}
          />
          <mesh
            geometry={nodes.Object_54.geometry}
            material={materials["Material.009"]}
            position={[0.11, 0.98, 0.05]}
            rotation={[-0.58, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_56.geometry}
            material={materials["Material.009"]}
            position={[-0.11, 0.98, 0.05]}
            rotation={[-0.58, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_4001.geometry}
            material={materials["Material.010"]}
            position={[0, 0.98, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={0.05}
          />
          <mesh
            geometry={nodes.Object_52.geometry}
            material={materials["Material.003"]}
            position={[0.89, 0.91, -0.94]}
          />
          <mesh
            geometry={nodes.Object_50.geometry}
            material={materials["Material.003"]}
            position={[1.11, 0.91, -0.94]}
          />
          <mesh
            geometry={nodes.Object_8001.geometry}
            material={materials["Material.009"]}
            position={[-0.32, 0.86, 0]}
            scale={0.03}
          />
          <mesh
            geometry={nodes.Object_6001.geometry}
            material={materials["Material.009"]}
            position={[0.32, 0.86, 0]}
            scale={0.03}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials["Material.004"]}
            position={[-0.06, 0.7, 0.04]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials["Material.004"]}
            position={[0.06, 0.71, 0.04]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials["Material.004"]}
            position={[0.06, 0.7, 0.04]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials["Material.004"]}
            position={[-0.06, 0.71, 0.04]}
            scale={0.01}
          />
        </group>
      )}
      {wing === 2 && (
        <group
          position={[0.04, 0.66, -0.14]}
          rotation={[-Math.PI / 2, 0, 3.14]}
          scale={0.12}
        >
          <mesh
            geometry={nodes.Object_2001.geometry}
            material={materials.aiStandardSurface1SG}
          />
          <mesh
            geometry={nodes.Object_3001.geometry}
            material={materials.aiStandardSurface3SG}
          />
          <mesh
            geometry={nodes.Object_4002.geometry}
            material={materials.aiStandardSurface4SG}
          />
          <mesh
            geometry={nodes.Object_5001.geometry}
            material={materials.aiStandardSurface5SG}
          />
          <mesh
            geometry={nodes.Object_6002.geometry}
            material={materials.aiStandardSurface1SG}
          />
          <mesh
            geometry={nodes.Object_7001.geometry}
            material={materials.aiStandardSurface2SG}
          />
          <mesh
            geometry={nodes.Object_8002.geometry}
            material={materials.aiStandardSurface3SG}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.aiStandardSurface4SG}
          />
        </group>
      )}
      {ear === 1 && (
        <group position={[0.04, 1.78, 0.08]} rotation={[0, 0.02, 0]} scale={0.0012}>
          <mesh
            geometry={nodes.Circle001_Material011_0.geometry}
            material={materials["Material.012"]}
            position={[-81.2, -41.98, -62.74]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={-30.05}
          />
          <mesh
            geometry={nodes.Circle014_Material005_0.geometry}
            material={materials["Material.013"]}
            position={[0, -18.53, -63.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Circle015_Material011_0.geometry}
            material={materials["Material.012"]}
            position={[81.32, -41.98, -62.74]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={30.05}
          />
          <mesh
            geometry={nodes.Circle016_Material007_0.geometry}
            material={materials["Material.014"]}
            position={[0, 39.29, -62.64]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Circle017_Material006_0.geometry}
            material={materials["Material.015"]}
            position={[0, 14.72, -63.03]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Circle018_Material010_0.geometry}
            material={materials["Material.016"]}
            position={[87.8, -41.98, -62.74]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={30.05}
          />
          <mesh
            geometry={nodes.Circle019_Material004_0.geometry}
            material={materials["Material.017"]}
            position={[62.9, -41.98, -62.74]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={30.05}
          />
          <mesh
            geometry={nodes.Circle021_Material010_0.geometry}
            material={materials["Material.016"]}
            position={[-87.77, -41.98, -62.74]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={-30.05}
          />
          <mesh
            geometry={nodes.Circle022_Material004_0.geometry}
            material={materials["Material.017"]}
            position={[-62.86, -41.98, -62.74]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={-30.05}
          />
          <mesh
            geometry={nodes.Circle023_Material012_0.geometry}
            material={materials["Material.018"]}
            position={[93.07, -41.98, -62.74]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={30.05}
          />
          <mesh
            geometry={nodes.Circle024_Material016_0.geometry}
            material={materials["Material.019"]}
            position={[-93.04, -41.98, -62.74]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={-30.05}
          />
          <mesh
            geometry={nodes.Cube004_Material008_0.geometry}
            material={materials["Material.020"]}
            position={[-50.08, 57.59, -63.59]}
            rotation={[Math.PI / 2, 0.53, 0]}
            scale={[-45.8, -45.8, -17.93]}
          />
          <mesh
            geometry={nodes.Cube008_Material001_0.geometry}
            material={materials["Material.021"]}
            position={[-51.99, 60.76, -58.81]}
            rotation={[Math.PI / 2, 0.53, 0]}
            scale={[-45.8, -45.8, -17.93]}
          />
          <mesh
            geometry={nodes.Cube010_Material008_0.geometry}
            material={materials["Material.020"]}
            position={[50.2, 57.59, -63.59]}
            rotation={[-Math.PI / 2, 0.53, 0]}
            scale={[45.8, 45.8, 17.93]}
          />
          <mesh
            geometry={nodes.Cube011_Material001_0.geometry}
            material={materials["Material.021"]}
            position={[52.11, 60.76, -58.81]}
            rotation={[-Math.PI / 2, 0.53, 0]}
            scale={[45.8, 45.8, 17.93]}
          />
          <mesh
            geometry={nodes.Cylinder003_Material014_0.geometry}
            material={materials["Material.022"]}
            position={[75.26, -77.07, -2.65]}
            rotation={[-2.68, 0, 0]}
            scale={[2.53, 2.53, 28.58]}
          />
          <mesh
            geometry={nodes.Cylinder004_Material015_0.geometry}
            material={materials["Material.023"]}
            position={[64.6, -85.47, 14.27]}
            rotation={[-2.68, 0, 0]}
            scale={[2.53, 2.53, 28.58]}
          />
          <mesh
            geometry={nodes.Cylinder005_Material013_0.geometry}
            material={materials["Material.024"]}
            position={[78.91, -60.23, -36.22]}
            rotation={[-2.68, 0, 0]}
            scale={[2.53, 2.53, 28.58]}
          />
        </group>
      )}
      {ear === 2 && (
        <group
          position={[0.04, 1.87, 0]}
          rotation={[-Math.PI / 2, 0, -0.02]}
          scale={0.04}
        >
          <mesh
            geometry={nodes.Electro_headphones_Material_1_0.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_1_0001.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_2_0.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_2_0001.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_2_0002.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_2_0003.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_3_0.geometry}
            material={materials.Material_3}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_4_0.geometry}
            material={materials.Material_4}
          />
          <mesh
            geometry={nodes.Electro_headphones_Material_4_0001.geometry}
            material={materials.Material_4}
          />
        </group>
      )}
      {glass === 1 && (
        <group position={[0.04, 1.73, 0.11]} rotation={[0, -0.02, 0]} scale={0.0011}>
          <mesh
            geometry={nodes.black_mesh_black_0.geometry}
            material={materials.black}
          />
          <mesh
            geometry={nodes.white_mesh_white_0.geometry}
            material={materials.white}
          />
        </group>
      )}
      {glass === 3 && (
        <group
          position={[-0.37, 1.18, -0.059]}
          rotation={[-Math.PI / 2, 0, 1.61]}
          scale={0.16}
        >
          <mesh
            geometry={nodes.Object_2002.geometry}
            material={materials["Material.018"]}
            position={[-0.61, -2.54, -5.63]}
            rotation={[0, 0, -1.58]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.Object_3002.geometry}
            material={materials["aiStandardSurface1SG.003"]}
            position={[-0.61, -2.54, -5.63]}
            rotation={[0, 0, -1.58]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.Object_4003.geometry}
            material={materials.maskstandardSurface1SG}
            position={[-0.61, -2.54, -5.63]}
            rotation={[0, 0, -1.58]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.Object_5002.geometry}
            material={materials.phongE1SG}
            position={[-0.61, -2.54, -5.63]}
            rotation={[0, 0, -1.58]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.Object_6003.geometry}
            material={materials.phongE1SG}
            position={[-0.61, -2.54, -5.63]}
            rotation={[0, 0, -1.58]}
            scale={0.06}
          />
        </group>
      )}
      {glass === 4 && (
        <group
          position={[0.04, 1.6, 0.028]}
          rotation={[Math.PI, -1.57, Math.PI]}
          scale={0.023}
        >
          <mesh
            geometry={nodes.Object_4004.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            geometry={nodes.Object_5003.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            geometry={nodes.Object_6004.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            geometry={nodes.Object_7002.geometry}
            material={materials.Nero}
          />
          <mesh
            geometry={nodes.Object_8003.geometry}
            material={materials.Rosso}
          />
          <mesh
            geometry={nodes.Object_9001.geometry}
            material={materials["material.001"]}
          />
        </group>
      )}
      {ear === 3 && (
        <mesh
          geometry={nodes.Gaming_Headset.geometry}
          material={materials.DefaultMaterial}
          position={[0.04, 1.85, 0]}
          rotation={[-1.57, -0.09, 1.57]}
          scale={0.004}
        />
      )}
      {ear === 4 && (
        <mesh
          geometry={nodes["Oculus_Headset_Low_Poly-ish"].geometry}
          material={materials["Material.025"]}
          position={[0.04, 1.75, 0.03]}
          rotation={[-Math.PI / 2, 0, 0.02]}
          scale={0.023}
        />
      )}

      {glass === 2 && (
        <mesh
          geometry={nodes.Cyclops_sunglasses.geometry}
          material={materials.Standard_1}
          position={[0.04, 1.73, 0.05]}
          rotation={[-Math.PI / 2, 0, -0.01]}
          scale={0.0009}
        />
      )}

      <group position={[0.04, 0, 0]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Object_11.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_13001.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Object_13001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_15.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Object_15.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_17001.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Object_17001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_19001.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Object_19001.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_21.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Object_21.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_23.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Object_23.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_7003.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.Object_7003.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9002.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.Object_9002.skeleton}
        />
        <primitive object={nodes.GLTF_created_0_rootJoint_1} />
        <skinnedMesh
          geometry={nodes.Object_21001.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Object_21001.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/customize/2-transformed.glb");
