export const TOGGLE_MODAL='TOGGLE_MODAL';
export const CHANGE_PROFILE='CHANGE_PROFILE';
export const CHANGE_THEME='CHANGE_THEME';
export const CHANGE_MODEL_CUSTOMIZE='CHANGE_MODEL_CUSTOMIZE';
export const CHANGE_CURRENT_MODEL='CHANGE_CURRENT_MODEL';