/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 cyberpunk_azura.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/templates/Humanoid_Mecha/cyberpunk_azura-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Body001_Body_0.geometry} material={materials.Body} />
        <mesh geometry={nodes.Body001_Head_0.geometry} material={materials.Head} />
        <mesh geometry={nodes.Body001_Other_0.geometry} material={materials.Other} />
        <mesh geometry={nodes.Body001_Weapon_0.geometry} material={materials.Weapon} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/templates/Humanoid_Mecha/cyberpunk_azura-transformed.glb')
