/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Expedition_mecha.glb -T
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/templates/Humanoid_Mecha/Expedition_mecha-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() =>{
    actions['Action'].play();
    
  }, []);
  return (
    <group ref={group} {...props} dispose={null} >
      <group name="Scene">
        <group name="Expedition_Mecha_Action">
          <group name="Object_4">
            <primitive object={nodes._rootJoint} />
            <group name="pCircle1" scale={134.25}>
              <mesh name="pCircle1_floor_0" geometry={nodes.pCircle1_floor_0.geometry} material={materials.floor} />
            </group>
            <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_11.skeleton} />
            <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_13.skeleton} />
            <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_15.skeleton} />
            <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_17.skeleton} />
            <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_19.skeleton} />
            <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_21.skeleton} />
            <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_23.skeleton} />
            <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_25.skeleton} />
            <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_27.skeleton} />
            <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_29.skeleton} />
            <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_31.skeleton} />
            <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_33.skeleton} />
            <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_35.skeleton} />
            <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_37.skeleton} />
            <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_39.skeleton} />
            <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_41.skeleton} />
            <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_43.skeleton} />
            <skinnedMesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_45.skeleton} />
            <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_47.skeleton} />
            <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_49.skeleton} />
            <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_51.skeleton} />
            <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_53.skeleton} />
            <skinnedMesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_55.skeleton} />
            <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_57.skeleton} />
            <skinnedMesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_59.skeleton} />
            <skinnedMesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_61.skeleton} />
            <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_63.skeleton} />
            <skinnedMesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_65.skeleton} />
            <skinnedMesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_67.skeleton} />
            <skinnedMesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_69.skeleton} />
            <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_71.skeleton} />
            <skinnedMesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_73.skeleton} />
            <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_75.skeleton} />
            <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_77.skeleton} />
            <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_79.skeleton} />
            <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_81.skeleton} />
            <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_83.skeleton} />
            <skinnedMesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_85.skeleton} />
            <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_87.skeleton} />
            <skinnedMesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_89.skeleton} />
            <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_9.skeleton} />
            <skinnedMesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_91.skeleton} />
            <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.Mecha_Mat} skeleton={nodes.Object_93.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/templates/Humanoid_Mecha/Expedition_mecha-transformed.glb')
