/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Human1.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/templates/Humanoid_Mecha/Human1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ModelGroup48843_Modellambert4SG1_0.geometry} material={materials.Modellambert4SG1} />
      <mesh geometry={nodes.ModelpolySurface21_Modellambert2SG1_0.geometry} material={materials.Modellambert2SG1} />
      <mesh geometry={nodes.ModelpolySurface21_Modellambert2SG1_0001.geometry} material={materials.Modellambert2SG1} />
      <mesh geometry={nodes.ModelpolySurface21_Modellambert3SG1_0.geometry} material={materials.Modellambert3SG1} />
    </group>
  )
}

useGLTF.preload('/models/templates/Humanoid_Mecha/Human1-transformed.glb')
