/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Robot_Dinosaur.glb -T
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/templates/Humanoid_Mecha/Robot_Dinosaur-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions["Kazurka@hit"].play();
    console.log(Object.keys(actions));
    // Object.keys(actions).forEach(element => {
    //   actions[element].play();
    // });
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Kazurka_-_Animated" scale={0.01}>
          <group name="Object_4">
            <primitive object={nodes._rootJoint} />
            <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.phong1} skeleton={nodes.Object_6.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/templates/Humanoid_Mecha/Robot_Dinosaur-transformed.glb')
