/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 cat1.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/templates/Animals/cat1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cat_3d.geometry} material={materials.material} rotation={[-3.12, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/templates/Animals/cat1-transformed.glb')
