/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 dog1.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/templates/Animals/dog1-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Hemi" position={[-0.53, 3.5, 3.18]} rotation={[0.27, -0.2, 0.01]} />
        <mesh name="Dog_Dachshund_-Tacskó" geometry={nodes['Dog_Dachshund_-Tacskó'].geometry} material={materials['null']} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/templates/Animals/dog1-transformed.glb')
