/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 rabbit.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/templates/Animals/rabbit-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rabbit.geometry} material={materials.material_0} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/templates/Animals/rabbit-transformed.glb')
