/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 robotdog.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/templates/Animals/robotdog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial060.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial061.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial059.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial007.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial052.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial057.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial009.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial054.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial058.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial055.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial056.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial030.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial040.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial004.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial008.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial017.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial048.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial014.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial045.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial013.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial044.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial019.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial050.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial018.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial049.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial024.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial034.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial020.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial051.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial015.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial046.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial016.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial047.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial010.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial041.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial011.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial042.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial028.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial038.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial023.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial033.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial029.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial039.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial022.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial032.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial012.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial043.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial027.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial037.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial026.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial036.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial025.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial035.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial021.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial031.geometry} material={materials.lambert3} />
      <mesh geometry={nodes.defaultMaterial053.geometry} material={materials.lambert3} />
    </group>
  )
}

useGLTF.preload('/models/templates/Animals/robotdog-transformed.glb')
