/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 futuristic_car.glb -T
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/templates/Cars/futuristic_car-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    // console.log(Object.keys(actions))
    actions['Action'].play();
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Futuristic_Car_Animation">
          <group name="Object_4">
            <group name="Cube_002" />
            <group name="Hemi" position={[-0.53, 3.5, 3.18]} rotation={[0.27, -0.2, 0.01]} />
            <primitive object={nodes._rootJoint} />
            <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Car__Speed_Car_A_1_png} skeleton={nodes.Object_10.skeleton} />
            <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Car__untitled_006} skeleton={nodes.Object_11.skeleton} />
            <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_002__untitled_001} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Material_001} skeleton={nodes.Object_8.skeleton} />
            <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Car__Speed_Car_c_png} skeleton={nodes.Object_9.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/templates/Cars/futuristic_car-transformed.glb')
