/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 hyper_concept_car.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/templates/Cars/hyper_concept_car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallay5group.geometry} material={materials.blinn27} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaygroup1.geometry} material={materials.headlight_smooth} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaygroup11_bl.geometry} material={materials.blinn41} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypCube4_bli.geometry} material={materials.blinn57} position={[0, 0.84, 3.26]} rotation={[0.52, 0, 0]} scale={[1, 2.07, 1]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypCube5_bli.geometry} material={materials.blinn58} position={[0, 7.05, -3.55]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.17, 2.43, 1.17]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu002.geometry} material={materials.taillight_basee} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu004.geometry} material={materials.blinn39} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu006.geometry} material={materials.blinn43} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu007.geometry} material={materials.blinn48} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu009.geometry} material={materials.blinn44} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu011.geometry} material={materials.Board_ctrl} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu012.geometry} material={materials.taillight_base} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu013.geometry} material={materials.blinn47} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu014.geometry} material={materials.blinn48} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu015.geometry} material={materials.blinn50} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu017.geometry} material={materials.blinn54} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredallaypolySu.geometry} material={materials.blinn33} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredconcept_engi003.geometry} material={materials.blinn66} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredconcept_engi.geometry} material={materials.metal_smooth} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredconcept_engi001.geometry} material={materials.metal_rough} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredGRILL_TEXTURE_bl.geometry} material={materials.blinn55} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredgroup10pSphere3_.geometry} material={materials.basterd} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredgroup19_blinn32_.geometry} material={materials.blinn32} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredgroup31_blinn69_.geometry} material={materials.blinn69} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredgroup32_blinn69_.geometry} material={materials.blinn69} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredgroup35_lambert1.geometry} material={materials.lambert11} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredgroup36_blinn56_.geometry} material={materials.blinn56} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredgroup37_blinn71_.geometry} material={materials.blinn33} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredmtod1polySu.geometry} material={materials.blinn61} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredmtod3mtodc002.geometry} material={materials.taillight_glow} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredmtod3mtodc.geometry} material={materials.headlght_rough} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredmtodconcept002.geometry} material={materials.inner_metal} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredmtodconcept.geometry} material={materials.blinn62} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredpCylinder4_blinn.geometry} material={materials.blinn89} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredpCylinder4_bolt_.geometry} material={materials.bolt} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredpPlane8_blinn51_.geometry} material={materials.blinn51} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredSPOILER_blinn70_.geometry} material={materials.blinn69} position={[0, -0.01, 4.19]} />
      <mesh geometry={nodes.Allay_concept_coloured1Allay_concept_colouredUPPER_HEAD_lambe.geometry} material={materials.lambert11} position={[0, -3.3, -1.83]} rotation={[0.35, 0, 0]} />
      <mesh geometry={nodes.Allay_concept_colouredmtod4allaypolySurface116_blinn52_0.geometry} material={materials.blinn52} />
      <mesh geometry={nodes.group10pPlane4_headlight_rough_0.geometry} material={materials.metal_rough} />
      <mesh geometry={nodes.group40_fuck_you_0.geometry} material={materials.fuck_you} />
      <mesh geometry={nodes.group44_pCube11_blinn48_0.geometry} material={materials.blinn48} />
      <mesh geometry={nodes.group44_polySurface67_blinn85_0.geometry} material={materials.blinn85} />
      <mesh geometry={nodes.group44_polySurface67_rim_glow_0.geometry} material={materials.rim_glow} />
      <mesh geometry={nodes.group45_polySurface63_blinn86_0.geometry} material={materials.blinn86} />
      <mesh geometry={nodes.H_blinn90_0.geometry} material={materials.blinn90} />
      <mesh geometry={nodes.pCube10_blinn42_0.geometry} material={materials.blinn42} position={[0, 0, 4.19]} />
      <mesh geometry={nodes.polySurface140_taillight_base_0.geometry} material={materials.taillight_base} position={[0, 0, 4.19]} />
      <mesh geometry={nodes.polySurface163_blinn30_0.geometry} material={materials.blinn30} />
      <mesh geometry={nodes.polySurface202_blinn60_0.geometry} material={materials.blinn60} />
      <mesh geometry={nodes.polySurface203_headlght_rough_0.geometry} material={materials.headlght_rough} />
      <mesh geometry={nodes.polySurface204_headlight_fiber_0.geometry} material={materials.headlight_fiber} />
      <mesh geometry={nodes.polySurface205_basterd_0.geometry} material={materials.basterd} />
      <mesh geometry={nodes.polySurface97_Headlight_base_0.geometry} material={materials.Headlight_base} />
      <mesh geometry={nodes.pPlane3_blinn56_0.geometry} material={materials.blinn56} />
      <mesh geometry={nodes.racing_rims_2lolpCylinder1_blinn87_0.geometry} material={materials.blinn87} />
      <mesh geometry={nodes.tyres1NAVIGATION_PEDALS_METAL_tyres1blinn18SG1_0.geometry} material={materials.tyres1blinn18SG1} position={[0.4, -0.15, 0.73]} scale={0.37} />
    </group>
  )
}

useGLTF.preload('/models/templates/Cars/hyper_concept_car-transformed.glb')
