/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 modern_supercar.glb -T
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/templates/Cars/modern_supercar-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions['Action'].play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Hemi" position={[-0.53, 3.5, 3.18]} rotation={[0.27, -0.2, 0.01]} />
        <group name="Afsona_-_Modern_Electric_Vehicle_-_Hyper_Car">
          <group name="BrakeCaliper001_3" scale={0.45}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.BrakeCaliperBlue} />
            <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.BrakeCaliperBlue} />
          </group>
          <group name="BrakeCaliper_60" scale={0.42}>
            <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.BrakeCaliperBlue} />
            <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.BrakeCaliperBlue} />
          </group>
          <group name="BrakeCover001_6" scale={0.46}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Rims.001']} />
          </group>
          <group name="BrakeCover_63" scale={0.43}>
            <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials['Rims.001']} />
          </group>
          <group name="BrakeSpin001_0" scale={0.45}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.TireBrake} />
          </group>
          <group name="BrakeSpin_57" scale={0.42}>
            <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.TireBrake} />
          </group>
          <group name="CarUnder_9" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <group name="SideAirRelease_7">
              <mesh name="Object_22001" geometry={nodes.Object_22001.geometry} material={materials.FrontGrille} />
            </group>
            <group name="SideRearAir_intake_8">
              <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.FrontGrille} />
            </group>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.CarUnder} />
          </group>
          <group name="DoorInside_37" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.BlackTemperedGlassRoof} />
          </group>
          <group name="Doors_11" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.CarBodyDarkBlue} />
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.WindowsGlass} />
          </group>
          <group name="FrontBonnetCover_14" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <group name="WindscreenWiper_13" position={[-0.28, 0, 1.5]} rotation={[0, 0.12, Math.PI / 2]} scale={0.1}>
              <group name="WindscreenWashers_12" position={[0, -4.73, -14.83]} rotation={[-0.12, 0, -Math.PI / 2]} scale={10.21}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.BlackTemperedGlassRoof} />
              </group>
              <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.BlackTemperedGlassRoof} />
            </group>
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.CarBodyDarkBlue} />
          </group>
          <group name="FrontCamera_36" position={[0, 0.34, 2.26]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.32}>
            <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.BlackTemperedGlassRoof} />
            <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.BlueCamera} />
            <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.RedCamera} />
          </group>
          <group name="FrontCarbonFiber_34" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <group name="FrontairIntake_28">
              <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.FrontGrille} />
            </group>
            <group name="FrontAirIntakeAroundMetal_29">
              <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.BlackMetallic} />
            </group>
            <group name="FrontLogo_30" position={[-0.01, 0, 2.28]} rotation={[0, 0.63, Math.PI / 2]} scale={0.44}>
              <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.LightMetal} />
            </group>
            <group name="HeadlightsCoverGlass_33">
              <group name="HeadlightsWhite_32" position={[0.41, 0, 0]} rotation={[0, 0, Math.PI / 2]} scale={0.38}>
                <group name="Headlights_31" scale={2.62}>
                  <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.HeadlightsInvisiblePart} />
                </group>
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.WindowsGlass} />
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.HeadlightsWhite} />
              </group>
              <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.HeadlightsGlass} />
            </group>
            <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.CarbonFiber} />
          </group>
          <group name="FrontWheelLogos_52" rotation={[Math.PI / 2, -0.03, -Math.PI / 2]} scale={0.28}>
            <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.LightMetal} />
          </group>
          <group name="InteriorMain_50" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <group name="_chairs_38" position={[0.41, 0, 0]} rotation={[0, 1.39, Math.PI / 2]} scale={0.01}>
              <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.Seats} />
            </group>
            <group name="Cube065_48" position={[0.29, 0.1, 0.13]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.07}>
              <group name="Cube066_39">
                <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.BlackMetallic} />
              </group>
              <group name="Cube070_40" rotation={[-Math.PI, 0, -Math.PI]} scale={0.45}>
                <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.BlackPlastic2} />
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.DarkerMetallic} />
              </group>
              <group name="Cube071_41" rotation={[-Math.PI, 0, -Math.PI]} scale={0.94}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Buttons.001']} />
                <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.RimBloodVeins} />
              </group>
              <group name="Cube072_42" rotation={[-Math.PI, 0, -Math.PI]} scale={0.94}>
                <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials['Buttons.001']} />
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.RimBloodVeins} />
              </group>
              <group name="Cube073_43" position={[-5.73, 7.19, -5.38]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.51}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.Buttons} />
              </group>
              <group name="Cube074_44">
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.BlackMetallic} />
              </group>
              <group name="Torus002_45">
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.DarkerMetallic} />
              </group>
              <group name="Torus003_46">
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.BlackMetallic} />
              </group>
              <group name="Torus004_47">
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.BlackMetallic} />
              </group>
              <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.CarbonFiber} />
            </group>
            <group name="InteriorBigScreen_49">
              <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.BlackTemperedGlassRoof} />
            </group>
            <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.InteriorVelvet} />
            <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.Seats} />
            <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.CarbonFiber} />
            <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.BlackTemperedGlassRoof} />
          </group>
          <group name="MainBody001_55" position={[0, 1.21, 0]} rotation={[0, 0, Math.PI / 2]}>
            <group name="TopSensorCap_54" position={[-0.81, 0, 0]} rotation={[0, 0, Math.PI]}>
              <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.CarBodyDarkBlue} />
            </group>
            <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.BlackTemperedGlassRoof} />
            <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.WindowsGlass} />
            <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.BluLineLight} />
          </group>
          <group name="MainBody_10" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.WindowsGlass} />
            <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.CarBodyDarkBlue} />
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.BlackTemperedGlassRoof} />
            <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.HeadlightsWhite} />
          </group>
          <group name="RearGrille_27" position={[0, 0.41, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <group name="ChargeCap_16" position={[-0.24, 0, -2.3]} scale={1.02}>
              <group name="ChargeCapLight_15">
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.RearLight4} />
              </group>
              <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.BlackTemperedGlassRoof} />
            </group>
            <group name="Name001_18" position={[-0.34, 0, -2.18]} rotation={[Math.PI, 1.27, Math.PI / 2]} scale={0.04}>
              <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.BlackTemperedGlassRoof} />
            </group>
            <group name="RearCarbonFiberGrille_20">
              <group name="RearCarbonFiberGrille001_19" position={[-0.02, 0, -0.01]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.CarbonFiber} />
                <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.RearLight5} />
              </group>
              <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.CarbonFiber} />
            </group>
            <group name="RearGrilleAroundMetal_21" position={[0, 0, 0.01]}>
              <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.BlackMetallic} />
            </group>
            <group name="RearLights001_23">
              <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.RearLight1} />
            </group>
            <group name="RearLights002_24">
              <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.RearLight3} />
              <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.CarBodyDarkBlue} />
            </group>
            <group name="RearLights_22">
              <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.CarBodyDarkBlue} />
              <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.RearLightsRed} />
            </group>
            <group name="RearSensorCaps_25">
              <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.CarBodyDarkBlue} />
            </group>
            <group name="Wing_26">
              <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.CarBodyDarkBlue} />
            </group>
            <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.FrontGrille} />
          </group>
          <group name="RearWheelLogos_53" position={[0, 0.02, -2.81]} rotation={[Math.PI / 2, -0.03, -Math.PI / 2]} scale={0.28}>
            <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.LightMetal} />
          </group>
          <group name="RimBolts001_5" rotation={[2.51, 0, -Math.PI / 2]} scale={0.35}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Rims} />
          </group>
          <group name="RimBolts_62" rotation={[2.51, 0, -Math.PI / 2]} scale={0.32}>
            <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.Rims} />
          </group>
          <group name="RimPentagonFlower001_4">
            <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Rims} />
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.RimBlueVeins} />
          </group>
          <group name="RimPentagonFlower_61" position={[0, 0.33, 1.31]} rotation={[2.51, 0, -Math.PI / 2]} scale={0.32}>
            <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.Rims} />
            <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.RimBlueVeins} />
          </group>
          <group name="Rims001_2" scale={0.4}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Rims} />
          </group>
          <group name="Rims_59" scale={0.37}>
            <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.Rims} />
          </group>
          <group name="RubberTire001_1" scale={0.38}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Tire} />
          </group>
          <group name="RubberTire_58" scale={0.35}>
            <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.Tire} />
          </group>
          <group name="UZBFlag_51" rotation={[0.01, 0.1, -0.07]} scale={0.85}>
            <mesh name="mesh_50002" geometry={nodes.mesh_50002.geometry} material={materials.UzbFlagWhite} />
            <mesh name="mesh_50" geometry={nodes.mesh_50.geometry} material={materials.UzbFlagGreen} morphTargetDictionary={nodes.mesh_50.morphTargetDictionary} morphTargetInfluences={nodes.mesh_50.morphTargetInfluences} />
            <mesh name="mesh_50001" geometry={nodes.mesh_50001.geometry} material={materials.UzbFlagBlue} morphTargetDictionary={nodes.mesh_50001.morphTargetDictionary} morphTargetInfluences={nodes.mesh_50001.morphTargetInfluences} />
          </group>
          <group name="WingCameras002_56" scale={0.32}>
            <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.CarBodyDarkBlue} />
          </group>
          <group name="WingCameras_35" scale={0.32}>
            <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.CarBodyDarkBlue} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/templates/Cars/modern_supercar-transformed.glb')
