/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 supercar.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/templates/Cars/supercar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[4.65, -5.93, 1.77]} rotation={[0, 0, -Math.PI / 9]} scale={0.95}>
          <mesh geometry={nodes.Disk1_0.geometry} material={materials['Disks.001']} />
          <mesh geometry={nodes.Disk1_1.geometry} material={materials['Brake.001']} />
          <mesh geometry={nodes.Tyre1_0.geometry} material={materials['Tyre.001']} position={[-4.58, 5.93, -1.77]} />
        </group>
        <group position={[-4.68, -5.93, 1.77]} rotation={[-Math.PI, 0, -2.79]} scale={0.95}>
          <mesh geometry={nodes.Disk1001_0.geometry} material={materials['Disks.001']} />
          <mesh geometry={nodes.Disk1001_1.geometry} material={materials['Brake.001']} />
          <mesh geometry={nodes.Tyre1001_0.geometry} material={materials['Tyre.001']} position={[-4.58, 5.93, -1.77]} />
        </group>
        <group position={[-4.68, 7.74, 1.77]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.95}>
          <mesh geometry={nodes.Disk1002_0.geometry} material={materials['Disks.001']} />
          <mesh geometry={nodes.Disk1002_1.geometry} material={materials['Brake.001']} />
          <mesh geometry={nodes.Tyre1002_0.geometry} material={materials['Tyre.001']} position={[-4.58, 5.93, -1.77]} />
        </group>
        <group position={[4.65, 7.74, 1.77]} scale={0.95}>
          <mesh geometry={nodes.Disk1003_0.geometry} material={materials['Disks.001']} />
          <mesh geometry={nodes.Disk1003_1.geometry} material={materials['Brake.001']} />
          <mesh geometry={nodes.Tyre1003_0.geometry} material={materials['Tyre.001']} position={[-4.58, 5.93, -1.77]} />
        </group>
        <group position={[0, -10.5, 3.02]} rotation={[0.52, 0, 0]} scale={0.06}>
          <mesh geometry={nodes.Logo_0.geometry} material={materials['Logo.001']} />
          <mesh geometry={nodes.Logo_1.geometry} material={materials['LogoFace.001']} />
        </group>
        <mesh geometry={nodes.CarBody_0.geometry} material={materials['CarSurface.001']} />
        <mesh geometry={nodes.CarBody_0001.geometry} material={materials['CarSurface.001']} />
        <mesh geometry={nodes.CarBody_0002.geometry} material={materials['CarSurface.001']} />
        <mesh geometry={nodes.CarBody_0003.geometry} material={materials['CarSurface.001']} />
        <mesh geometry={nodes.CarBody_1.geometry} material={materials['HeadlightsEdge.001']} />
        <mesh geometry={nodes.CarBody_2.geometry} material={materials['Tumanka.001']} />
        <mesh geometry={nodes.CarBody_3.geometry} material={materials['BacklightEdge.001']} />
        <mesh geometry={nodes.CarBody_4.geometry} material={materials['Backlight.001']} />
        <mesh geometry={nodes.CarBody_5.geometry} material={materials['ExhaustPipeEdge.001']} />
        <mesh geometry={nodes.CarBody_6.geometry} material={materials['ExhaustPipe.001']} />
        <mesh geometry={nodes.CarBody_7.geometry} material={materials['Doorstep.001']} />
        <mesh geometry={nodes.CarBody001_0.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.CarBody002_0.geometry} material={materials['Headlights.001']} />
        <mesh geometry={nodes.CarBody002_1.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.CarBody003_0.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.CarBody004_0.geometry} material={materials['Backlight.001']} />
        <mesh geometry={nodes.CarBody004_1.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.CarBody005_0.geometry} material={materials['ChargeLid.001']} />
        <mesh geometry={nodes.Charger_0.geometry} material={materials['ChargeIcon.001']} />
        <mesh geometry={nodes.SideMirrors_0.geometry} material={materials['CarSurface.001']} />
        <mesh geometry={nodes.SideMirrors001_0.geometry} material={materials['Glass.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/templates/Cars/supercar-transformed.glb')
