/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 blue_wings.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blue_wings-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['aiStandardSurface1SG.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.aiStandardSurface6SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['aiStandardSurface1SG.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['aiStandardSurface2SG.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['aiStandardSurface3SG.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['aiStandardSurface4SG.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.aiStandardSurface6SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/blue_wings-transformed.glb')
