/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 cleaver_sword.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cleaver_sword-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.BladeMain} />
        <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.BladeBody} />
        <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.Hilt1} />
        <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.BladeTop} />
        <mesh geometry={nodes.defaultMaterial004.geometry} material={materials.Hilt2} />
        <mesh geometry={nodes.defaultMaterial005.geometry} material={materials['phong1.001']} />
        <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.Handle} />
      </group>
    </group>
  )
}

useGLTF.preload('/cleaver_sword-transformed.glb')
