/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 futuristic_katana.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/futuristic_katana-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.012']} position={[0, -0.33, 3]} rotation={[0.06, 0, 0]} scale={10} />
    </group>
  )
}

useGLTF.preload('/futuristic_katana-transformed.glb')
