/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 oxidated_armour.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/oxidated_armour-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Default} />
      </group>
    </group>
  )
}

useGLTF.preload('/oxidated_armour-transformed.glb')
