/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 radioactive_raider_sword.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/radioactive_raider_sword-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.23, 0.99]} rotation={[-0.55, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Battery} />
        <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.Blade} />
        <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.Wire} />
        <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.Grip2} />
        <mesh geometry={nodes.defaultMaterial004.geometry} material={materials.Hilt} />
        <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.Grip1} />
      </group>
    </group>
  )
}

useGLTF.preload('/radioactive_raider_sword-transformed.glb')
