/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scifi_face_mask.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scifi_face_mask-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.81, 1.45, 0.87]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Material_001-material'].geometry} material={materials.Material_001} />
        <mesh geometry={nodes['Material_002-material'].geometry} material={materials.Material_002} />
        <mesh geometry={nodes['Material_003-material'].geometry} material={materials.Material_003} />
        <mesh geometry={nodes['Material_004-material'].geometry} material={materials.Material_004} />
        <mesh geometry={nodes['Material_005-material'].geometry} material={materials.Material_005} />
      </group>
    </group>
  )
}

useGLTF.preload('/scifi_face_mask-transformed.glb')
